-- MySQL Script generated by MySQL Workbench
-- Mon Oct 19 22:28:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Organizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Organizador` (
  `idOrganizador` TEXT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` TEXT NULL,
  `razaoSocial` VARCHAR(45) NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `cnpj` VARCHAR(18) NULL,
  PRIMARY KEY (`idOrganizador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` TEXT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` TEXT NULL,
  `cpf` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` TEXT NOT NULL,
  `rua` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `uf` CHAR(2) NULL,
  `complemento` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `Organizador_idOrganizador` TEXT NULL,
  `Cliente_idCliente` TEXT NULL,
  `tipo` ENUM("COMERCIAL", "COBRANCA") NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Organizador_idx` (`Organizador_idOrganizador` ASC) VISIBLE,
  INDEX `fk_Endereco_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Organizador`
    FOREIGN KEY (`Organizador_idOrganizador`)
    REFERENCES `mydb`.`Organizador` (`idOrganizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` TEXT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `destaque` TINYINT(1) NULL,
  `faixaEtaria` VARCHAR(45) NULL,
  `Endereco_idEndereco` TEXT NOT NULL,
  PRIMARY KEY (`idEvento`, `Endereco_idEndereco`),
  INDEX `fk_Evento_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arquivo` (
  `idArquivo` TEXT NOT NULL,
  `dataUpload` DATE NULL,
  `caminhoArquivo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `Organizador_idOrganizador` TEXT NULL,
  `Cliente_idCliente` TEXT NULL,
  `Evento_idEvento` TEXT NULL,
  PRIMARY KEY (`idArquivo`, `Evento_idEvento`),
  INDEX `fk_Arquivo_Organizador1_idx` (`Organizador_idOrganizador` ASC) VISIBLE,
  INDEX `fk_Arquivo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Arquivo_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  CONSTRAINT `fk_Arquivo_Organizador1`
    FOREIGN KEY (`Organizador_idOrganizador`)
    REFERENCES `mydb`.`Organizador` (`idOrganizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arquivo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arquivo_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDeProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDeProduto` (
  `idTipoDeProduto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDeProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` TEXT NOT NULL,
  `nomeProduto` VARCHAR(45) NULL,
  `preco` DOUBLE NULL,
  `precoEspecial` DOUBLE NULL,
  `dataInicioPromocao` DATE NULL,
  `dataFimPromocao` DATE NULL,
  `Evento_idEvento` TEXT NOT NULL,
  `TipoDeProduto_idTipoDeProduto` INT NOT NULL,
  `SKU` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_Produto_TipoDeProduto1_idx` (`TipoDeProduto_idTipoDeProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_TipoDeProduto1`
    FOREIGN KEY (`TipoDeProduto_idTipoDeProduto`)
    REFERENCES `mydb`.`TipoDeProduto` (`idTipoDeProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CategoriaProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CategoriaProduto` (
  `idCategoriaProduto` TEXT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `categoriaPai_idCategoria` TEXT NOT NULL,
  PRIMARY KEY (`idCategoriaProduto`),
  INDEX `fk_CategoriaProduto_CategoriaProduto1_idx` (`categoriaPai_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_CategoriaProduto_CategoriaProduto1`
    FOREIGN KEY (`categoriaPai_idCategoria`)
    REFERENCES `mydb`.`CategoriaProduto` (`idCategoriaProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` TEXT NOT NULL,
  `data` DATE NULL,
  `valorOriginal` FLOAT NULL,
  `valorEspecial` FLOAT NULL,
  `codigoRetirada` VARCHAR(45) NULL,
  `Endereco_idEndereco` TEXT NOT NULL,
  `status` ENUM("PENDENTE", "EM_ANDAMENTO", "CONCLUIDO") NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho` (
  `idCarrinho` TEXT NOT NULL,
  `valorTotal` DOUBLE NULL,
  `Carrinhocol` VARCHAR(45) NULL,
  `Pedido_idPedido` TEXT NOT NULL,
  PRIMARY KEY (`idCarrinho`),
  INDEX `fk_Carrinho_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Carrinho_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PromocaoCarrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PromocaoCarrinho` (
  `idPromocaoCarrinho` INT NOT NULL,
  `dataInicio` DATE NULL,
  `dataFim` DATE NULL,
  `cupom` VARCHAR(45) NULL,
  `parametroPreco` FLOAT NULL,
  PRIMARY KEY (`idPromocaoCarrinho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento` (
  `idPagamento` TEXT NOT NULL,
  `data` DATE NULL,
  `valor` FLOAT NULL,
  `Pedido_idPedido` TEXT NOT NULL,
  `status` ENUM("PROCESSANDO", "PAGO", "CANCELADO") NULL,
  `hash` TEXT NULL,
  PRIMARY KEY (`idPagamento`),
  INDEX `fk_Pagamento_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_CategoriaProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_CategoriaProduto` (
  `Produto_idProduto` TEXT NOT NULL,
  `CategoriaProduto_idCategoriaProduto` TEXT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `CategoriaProduto_idCategoriaProduto`),
  INDEX `fk_Produto_has_CategoriaProduto_CategoriaProduto1_idx` (`CategoriaProduto_idCategoriaProduto` ASC) VISIBLE,
  INDEX `fk_Produto_has_CategoriaProduto_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_CategoriaProduto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_CategoriaProduto_CategoriaProduto1`
    FOREIGN KEY (`CategoriaProduto_idCategoriaProduto`)
    REFERENCES `mydb`.`CategoriaProduto` (`idCategoriaProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Carrinho` (
  `Produto_idProduto` TEXT NOT NULL,
  `Carrinho_idCarrinho` TEXT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Carrinho_idCarrinho`),
  INDEX `fk_Produto_has_Carrinho_Carrinho1_idx` (`Carrinho_idCarrinho` ASC) VISIBLE,
  INDEX `fk_Produto_has_Carrinho_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Carrinho_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Carrinho_Carrinho1`
    FOREIGN KEY (`Carrinho_idCarrinho`)
    REFERENCES `mydb`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrinho_has_PromocaoCarrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrinho_has_PromocaoCarrinho` (
  `Carrinho_idCarrinho` TEXT NOT NULL,
  `PromocaoCarrinho_idPromocaoCarrinho` INT NOT NULL,
  PRIMARY KEY (`Carrinho_idCarrinho`, `PromocaoCarrinho_idPromocaoCarrinho`),
  INDEX `fk_Carrinho_has_PromocaoCarrinho_PromocaoCarrinho1_idx` (`PromocaoCarrinho_idPromocaoCarrinho` ASC) VISIBLE,
  INDEX `fk_Carrinho_has_PromocaoCarrinho_Carrinho1_idx` (`Carrinho_idCarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_Carrinho_has_PromocaoCarrinho_Carrinho1`
    FOREIGN KEY (`Carrinho_idCarrinho`)
    REFERENCES `mydb`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrinho_has_PromocaoCarrinho_PromocaoCarrinho1`
    FOREIGN KEY (`PromocaoCarrinho_idPromocaoCarrinho`)
    REFERENCES `mydb`.`PromocaoCarrinho` (`idPromocaoCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrientacaoSexual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrientacaoSexual` (
  `idOrientacaoSexual` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idOrientacaoSexual`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDeEvento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDeEvento` (
  `idTipoDeEvento` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDeEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GeneroMusical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GeneroMusical` (
  `idGeneroMusical` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idGeneroMusical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preco` (
  `idPreco` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `precoMedio` FLOAT NULL,
  PRIMARY KEY (`idPreco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_has_OrientacaoSexual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento_has_OrientacaoSexual` (
  `Evento_idEvento` TEXT NOT NULL,
  `OrientacaoSexual_idOrientacaoSexual` INT NOT NULL,
  PRIMARY KEY (`Evento_idEvento`, `OrientacaoSexual_idOrientacaoSexual`),
  INDEX `fk_Evento_has_OrientacaoSexual_OrientacaoSexual1_idx` (`OrientacaoSexual_idOrientacaoSexual` ASC) VISIBLE,
  INDEX `fk_Evento_has_OrientacaoSexual_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_has_OrientacaoSexual_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_OrientacaoSexual_OrientacaoSexual1`
    FOREIGN KEY (`OrientacaoSexual_idOrientacaoSexual`)
    REFERENCES `mydb`.`OrientacaoSexual` (`idOrientacaoSexual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preco_has_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preco_has_Evento` (
  `Preco_idPreco` INT NOT NULL,
  `Evento_idEvento` TEXT NOT NULL,
  PRIMARY KEY (`Preco_idPreco`, `Evento_idEvento`),
  INDEX `fk_Preco_has_Evento_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_Preco_has_Evento_Preco1_idx` (`Preco_idPreco` ASC) VISIBLE,
  CONSTRAINT `fk_Preco_has_Evento_Preco1`
    FOREIGN KEY (`Preco_idPreco`)
    REFERENCES `mydb`.`Preco` (`idPreco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preco_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDeEvento_has_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDeEvento_has_Evento` (
  `TipoDeEvento_idTipoDeEvento` INT NOT NULL,
  `Evento_idEvento` TEXT NOT NULL,
  PRIMARY KEY (`TipoDeEvento_idTipoDeEvento`, `Evento_idEvento`),
  INDEX `fk_TipoDeEvento_has_Evento_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_TipoDeEvento_has_Evento_TipoDeEvento1_idx` (`TipoDeEvento_idTipoDeEvento` ASC) VISIBLE,
  CONSTRAINT `fk_TipoDeEvento_has_Evento_TipoDeEvento1`
    FOREIGN KEY (`TipoDeEvento_idTipoDeEvento`)
    REFERENCES `mydb`.`TipoDeEvento` (`idTipoDeEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoDeEvento_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GeneroMusical_has_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GeneroMusical_has_Evento` (
  `GeneroMusical_idGeneroMusical` INT NOT NULL,
  `Evento_idEvento` TEXT NOT NULL,
  PRIMARY KEY (`GeneroMusical_idGeneroMusical`, `Evento_idEvento`),
  INDEX `fk_GeneroMusical_has_Evento_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_GeneroMusical_has_Evento_GeneroMusical1_idx` (`GeneroMusical_idGeneroMusical` ASC) VISIBLE,
  CONSTRAINT `fk_GeneroMusical_has_Evento_GeneroMusical1`
    FOREIGN KEY (`GeneroMusical_idGeneroMusical`)
    REFERENCES `mydb`.`GeneroMusical` (`idGeneroMusical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GeneroMusical_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
